package com.itexicoapps.androidstock.constants

const val M_PRIMARY = "materialColors.colorPrimary"
const val M_PRIMARY_VARIANT = "materialColors.colorPrimaryVariant"
const val M_ON_PRIMARY = "materialColors.colorOnPrimary"
const val M_ON_PRIMARY_VARIANT = "materialColors.colorOnPrimaryVariant"
const val M_SECONDARY = "materialColors.colorSecondary"
const val M_SECONDARY_VARIANT = "materialColors.colorSecondaryVariant"
const val M_ON_SECONDARY = "materialColors.colorOnSecondary"
const val M_ON_SECONDARY_VARIANT = "materialColors.colorOnSecondaryVariant"
const val M_BACKGROUND = "materialColors.backgroundColor"
const val M_BACKGROUND_VARIANT = "materialColors.backgroundColorVariant"
const val M_ON_BACKGROUND = "materialColors.colorOnBackground"
const val M_ON_BACKGROUND_VARIANT = "materialColors.colorOnBackgroundVariant"
const val M_SURFACE = "materialColors.colorSurface"
const val M_ON_SURFACE = "materialColors.colorOnSurface"
const val M_ON_SURFACE_VARIANT = "materialColors.colorOnSurfaceVariant"
const val M_ERROR = "materialColors.colorError"
const val M_ON_ERROR = "materialColors.colorOnError"

const val LOGIN_LOGO_IMAGE = "brandImages.loginImage"
const val POP_UP_WHITE_IMAGE = "brandImages.whitePopupImage"
const val NO_INFO_IMAGE = "brandImages.noInfoImage"
const val APP_MENU_IMAGE = "brandImages.appMenuImage"
